/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as BranchIndexRouteImport } from './routes/branch/index'
import { Route as BranchIdRouteImport } from './routes/branch/$id'
import { Route as CodexIndexRouteImport } from './routes/codex/index'
import { Route as CodexLoreRouteImport } from './routes/codex/lore'
import { Route as CodexSpeciesRouteImport } from './routes/codex/species'
import { Route as CodexUiRouteImport } from './routes/codex/ui'
import { Route as CodexUnplacedRouteImport } from './routes/codex/unplaced'
import { Route as ExploreIndexRouteImport } from './routes/explore/index'
import { Route as GameSlugRouteImport } from './routes/game/$slug'
import { Route as GlossaryIndexRouteImport } from './routes/glossary/index'
import { Route as ThreadsIndexRouteImport } from './routes/threads/index'
import { Route as ThreadsIdRouteImport } from './routes/threads/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const BranchIndexRoute = BranchIndexRouteImport.update({
  id: '/branch/',
  path: '/branch/',
  getParentRoute: () => rootRouteImport,
} as any)
const BranchIdRoute = BranchIdRouteImport.update({
  id: '/branch/$id',
  path: '/branch/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CodexIndexRoute = CodexIndexRouteImport.update({
  id: '/codex/',
  path: '/codex/',
  getParentRoute: () => rootRouteImport,
} as any)
const CodexLoreRoute = CodexLoreRouteImport.update({
  id: '/codex/lore',
  path: '/codex/lore',
  getParentRoute: () => rootRouteImport,
} as any)
const CodexSpeciesRoute = CodexSpeciesRouteImport.update({
  id: '/codex/species',
  path: '/codex/species',
  getParentRoute: () => rootRouteImport,
} as any)
const CodexUiRoute = CodexUiRouteImport.update({
  id: '/codex/ui',
  path: '/codex/ui',
  getParentRoute: () => rootRouteImport,
} as any)
const CodexUnplacedRoute = CodexUnplacedRouteImport.update({
  id: '/codex/unplaced',
  path: '/codex/unplaced',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreIndexRoute = ExploreIndexRouteImport.update({
  id: '/explore/',
  path: '/explore/',
  getParentRoute: () => rootRouteImport,
} as any)
const GameSlugRoute = GameSlugRouteImport.update({
  id: '/game/$slug',
  path: '/game/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GlossaryIndexRoute = GlossaryIndexRouteImport.update({
  id: '/glossary/',
  path: '/glossary/',
  getParentRoute: () => rootRouteImport,
} as any)
const ThreadsIndexRoute = ThreadsIndexRouteImport.update({
  id: '/threads/',
  path: '/threads/',
  getParentRoute: () => rootRouteImport,
} as any)
const ThreadsIdRoute = ThreadsIdRouteImport.update({
  id: '/threads/$id',
  path: '/threads/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/stats': typeof StatsRoute
  '/branch/$id': typeof BranchIdRoute
  '/codex/lore': typeof CodexLoreRoute
  '/codex/species': typeof CodexSpeciesRoute
  '/codex/ui': typeof CodexUiRoute
  '/codex/unplaced': typeof CodexUnplacedRoute
  '/game/$slug': typeof GameSlugRoute
  '/threads/$id': typeof ThreadsIdRoute
  '/branch/': typeof BranchIndexRoute
  '/codex/': typeof CodexIndexRoute
  '/explore/': typeof ExploreIndexRoute
  '/glossary/': typeof GlossaryIndexRoute
  '/threads/': typeof ThreadsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/stats': typeof StatsRoute
  '/branch/$id': typeof BranchIdRoute
  '/codex/lore': typeof CodexLoreRoute
  '/codex/species': typeof CodexSpeciesRoute
  '/codex/ui': typeof CodexUiRoute
  '/codex/unplaced': typeof CodexUnplacedRoute
  '/game/$slug': typeof GameSlugRoute
  '/threads/$id': typeof ThreadsIdRoute
  '/branch': typeof BranchIndexRoute
  '/codex': typeof CodexIndexRoute
  '/explore': typeof ExploreIndexRoute
  '/glossary': typeof GlossaryIndexRoute
  '/threads': typeof ThreadsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/stats': typeof StatsRoute
  '/branch/$id': typeof BranchIdRoute
  '/codex/lore': typeof CodexLoreRoute
  '/codex/species': typeof CodexSpeciesRoute
  '/codex/ui': typeof CodexUiRoute
  '/codex/unplaced': typeof CodexUnplacedRoute
  '/game/$slug': typeof GameSlugRoute
  '/threads/$id': typeof ThreadsIdRoute
  '/branch/': typeof BranchIndexRoute
  '/codex/': typeof CodexIndexRoute
  '/explore/': typeof ExploreIndexRoute
  '/glossary/': typeof GlossaryIndexRoute
  '/threads/': typeof ThreadsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/stats'
    | '/branch/$id'
    | '/codex/lore'
    | '/codex/species'
    | '/codex/ui'
    | '/codex/unplaced'
    | '/game/$slug'
    | '/threads/$id'
    | '/branch/'
    | '/codex/'
    | '/explore/'
    | '/glossary/'
    | '/threads/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/stats'
    | '/branch/$id'
    | '/codex/lore'
    | '/codex/species'
    | '/codex/ui'
    | '/codex/unplaced'
    | '/game/$slug'
    | '/threads/$id'
    | '/branch'
    | '/codex'
    | '/explore'
    | '/glossary'
    | '/threads'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/stats'
    | '/branch/$id'
    | '/codex/lore'
    | '/codex/species'
    | '/codex/ui'
    | '/codex/unplaced'
    | '/game/$slug'
    | '/threads/$id'
    | '/branch/'
    | '/codex/'
    | '/explore/'
    | '/glossary/'
    | '/threads/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  StatsRoute: typeof StatsRoute
  BranchIdRoute: typeof BranchIdRoute
  CodexLoreRoute: typeof CodexLoreRoute
  CodexSpeciesRoute: typeof CodexSpeciesRoute
  CodexUiRoute: typeof CodexUiRoute
  CodexUnplacedRoute: typeof CodexUnplacedRoute
  GameSlugRoute: typeof GameSlugRoute
  ThreadsIdRoute: typeof ThreadsIdRoute
  BranchIndexRoute: typeof BranchIndexRoute
  CodexIndexRoute: typeof CodexIndexRoute
  ExploreIndexRoute: typeof ExploreIndexRoute
  GlossaryIndexRoute: typeof GlossaryIndexRoute
  ThreadsIndexRoute: typeof ThreadsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branch/': {
      id: '/branch/'
      path: '/branch'
      fullPath: '/branch/'
      preLoaderRoute: typeof BranchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branch/$id': {
      id: '/branch/$id'
      path: '/branch/$id'
      fullPath: '/branch/$id'
      preLoaderRoute: typeof BranchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/codex/': {
      id: '/codex/'
      path: '/codex'
      fullPath: '/codex/'
      preLoaderRoute: typeof CodexIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/codex/lore': {
      id: '/codex/lore'
      path: '/codex/lore'
      fullPath: '/codex/lore'
      preLoaderRoute: typeof CodexLoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/codex/species': {
      id: '/codex/species'
      path: '/codex/species'
      fullPath: '/codex/species'
      preLoaderRoute: typeof CodexSpeciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/codex/ui': {
      id: '/codex/ui'
      path: '/codex/ui'
      fullPath: '/codex/ui'
      preLoaderRoute: typeof CodexUiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/codex/unplaced': {
      id: '/codex/unplaced'
      path: '/codex/unplaced'
      fullPath: '/codex/unplaced'
      preLoaderRoute: typeof CodexUnplacedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/': {
      id: '/explore/'
      path: '/explore'
      fullPath: '/explore/'
      preLoaderRoute: typeof ExploreIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/$slug': {
      id: '/game/$slug'
      path: '/game/$slug'
      fullPath: '/game/$slug'
      preLoaderRoute: typeof GameSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glossary/': {
      id: '/glossary/'
      path: '/glossary'
      fullPath: '/glossary/'
      preLoaderRoute: typeof GlossaryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/threads/': {
      id: '/threads/'
      path: '/threads'
      fullPath: '/threads/'
      preLoaderRoute: typeof ThreadsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/threads/$id': {
      id: '/threads/$id'
      path: '/threads/$id'
      fullPath: '/threads/$id'
      preLoaderRoute: typeof ThreadsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  StatsRoute: StatsRoute,
  BranchIdRoute: BranchIdRoute,
  CodexLoreRoute: CodexLoreRoute,
  CodexSpeciesRoute: CodexSpeciesRoute,
  CodexUiRoute: CodexUiRoute,
  CodexUnplacedRoute: CodexUnplacedRoute,
  GameSlugRoute: GameSlugRoute,
  ThreadsIdRoute: ThreadsIdRoute,
  BranchIndexRoute: BranchIndexRoute,
  CodexIndexRoute: CodexIndexRoute,
  ExploreIndexRoute: ExploreIndexRoute,
  GlossaryIndexRoute: GlossaryIndexRoute,
  ThreadsIndexRoute: ThreadsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
